name: build
run-name: Oya build triggered by ${{ github.actor }}
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod
      - run: go build oya.go
      - uses: actions/upload-artifact@v3
        with:
          name: oya-current-build
          path: oya

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: oya-current-build
      - run: chmod +x oya
      - uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod
      - run: wget https://github.com/mozilla/sops/releases/download/3.3.1/sops_3.3.1_amd64.deb
      - run: sudo dpkg -i sops_3.3.1_amd64.deb
      - run: ./oya run develop
      - run: ./oya run testKeysImport
      - run: ./oya run test -t "~@nocircleci"
      - run: ./oya run testKeysRemove
